// ── Breastfeeding Support Resource Database ──
// Seeded starter dataset. Production: migrate to Firestore collection.

export const BF_SUPPORT_DB = [
  // ═══ GLOBAL ═══
  { id:"global-ilca", country_code:"GLOBAL", name:"ILCA Find a Lactation Consultant", description:"International directory to find an IBCLC lactation consultant near you.", support_type:"professional_directory", support_scope:"global", contact:{phone:null,tdd:null,email:null,whatsapp:null}, source_url:"https://ilca.org/why-ibclc-falc/", languages:["en"], region:null, city:null, postcode_prefix:null, lat:null, lng:null, is_24_7:false, is_remote:true, is_in_person:false, trust_level:"professional_directory", trigger_tags:["tongue_tie","latch_pain","nipple_pain","low_supply","poor_weight_gain","manual_request"], eligibility:null, service_hours:null, notes:"Global directory — search by location", active:true, verified_at:"2025-06-15", last_checked_at:"2025-06-15" },
  { id:"global-ibclc-care", country_code:"GLOBAL", name:"IBCLC Care Directory", description:"Find an IBCLC-staffed facility near you worldwide.", support_type:"professional_directory", support_scope:"global", contact:{phone:null,tdd:null,email:null,whatsapp:null}, source_url:"https://ibclccare.org/ibclc-care-directory/", languages:["en"], region:null, city:null, postcode_prefix:null, lat:null, lng:null, is_24_7:false, is_remote:true, is_in_person:false, trust_level:"professional_directory", trigger_tags:["tongue_tie","latch_pain","nipple_pain","low_supply","poor_weight_gain","manual_request"], eligibility:null, service_hours:null, notes:"Facility-level IBCLC directory", active:true, verified_at:"2025-06-15", last_checked_at:"2025-06-15" },
  { id:"global-ibclc-registry", country_code:"GLOBAL", name:"Public IBCLC Registry", description:"Verify IBCLC credentials and find certified lactation consultants.", support_type:"credential_verification", support_scope:"global", contact:{phone:null,tdd:null,email:null,whatsapp:null}, source_url:"https://ibclc-commission.org/public-registry/", languages:["en"], region:null, city:null, postcode_prefix:null, lat:null, lng:null, is_24_7:false, is_remote:true, is_in_person:false, trust_level:"professional_directory", trigger_tags:["tongue_tie","manual_request"], eligibility:null, service_hours:null, notes:"Credential verification registry", active:true, verified_at:"2025-06-15", last_checked_at:"2025-06-15" },

  // ═══ UNITED KINGDOM ═══
  { id:"uk-nbh", country_code:"GB", name:"National Breastfeeding Helpline", description:"Free confidential support from trained breastfeeding counsellors.", support_type:"helpline", support_scope:"national", contact:{phone:"0300 100 0212",tdd:null,email:null,whatsapp:null}, source_url:"https://www.nationalbreastfeedinghelpline.org.uk/", languages:["en"], region:null, city:null, postcode_prefix:null, lat:null, lng:null, is_24_7:false, is_remote:true, is_in_person:false, trust_level:"registered_charity", trigger_tags:["latch_pain","nipple_pain","low_supply","cluster_feeding","unsettled_after_feeds","engorgement","mastitis_concern","tongue_tie","low_confidence","poor_weight_gain","manual_request"], eligibility:null, service_hours:"9:30am-9:30pm daily", notes:null, active:true, verified_at:"2025-06-15", last_checked_at:"2025-06-15" },
  { id:"uk-nct", country_code:"GB", name:"NCT Infant Feeding Line", description:"Practical and emotional support for all infant feeding decisions.", support_type:"helpline", support_scope:"national", contact:{phone:"0300 330 0700",tdd:null,email:null,whatsapp:null}, source_url:"https://www.nct.org.uk/information/baby-toddler/feeding-your-baby-or-toddler/breastfeeding-support-nct", languages:["en"], region:null, city:null, postcode_prefix:null, lat:null, lng:null, is_24_7:false, is_remote:true, is_in_person:false, trust_level:"registered_charity", trigger_tags:["latch_pain","low_supply","cluster_feeding","low_confidence","manual_request"], eligibility:null, service_hours:"8am-midnight daily", notes:null, active:true, verified_at:"2025-06-15", last_checked_at:"2025-06-15" },
  { id:"uk-lll", country_code:"GB", name:"La Leche League GB", description:"Peer support, local groups, and trained leaders. Overnight helpline available.", support_type:"peer_support", support_scope:"national", contact:{phone:null,tdd:null,email:null,whatsapp:null}, source_url:"https://laleche.org.uk/find-lll-support-group/", languages:["en"], region:null, city:null, postcode_prefix:null, lat:null, lng:null, is_24_7:false, is_remote:true, is_in_person:true, trust_level:"peer_organisation", trigger_tags:["latch_pain","nipple_pain","low_supply","cluster_feeding","unsettled_after_feeds","engorgement","tongue_tie","low_confidence","manual_request"], eligibility:null, service_hours:null, notes:"Find local groups on website. Overnight helpline available.", active:true, verified_at:"2025-06-15", last_checked_at:"2025-06-15" },
  { id:"uk-abm", country_code:"GB", name:"Association of Breastfeeding Mothers", description:"Trained peer counsellors offering phone, email, and group support.", support_type:"peer_support", support_scope:"national", contact:{phone:null,tdd:null,email:null,whatsapp:null}, source_url:"https://abm.me.uk/", languages:["en"], region:null, city:null, postcode_prefix:null, lat:null, lng:null, is_24_7:false, is_remote:true, is_in_person:true, trust_level:"registered_charity", trigger_tags:["latch_pain","low_supply","cluster_feeding","low_confidence","manual_request"], eligibility:null, service_hours:null, notes:null, active:true, verified_at:"2025-06-15", last_checked_at:"2025-06-15" },
  { id:"uk-koala", country_code:"GB", name:"Koala", description:"Digital breastfeeding support with specialist video consultations.", support_type:"digital", support_scope:"national", contact:{phone:null,tdd:null,email:null,whatsapp:null}, source_url:"https://www.koala.health/", languages:["en"], region:null, city:null, postcode_prefix:null, lat:null, lng:null, is_24_7:false, is_remote:true, is_in_person:false, trust_level:"registered_charity", trigger_tags:["latch_pain","nipple_pain","low_supply","tongue_tie","low_confidence","manual_request"], eligibility:"Some areas have NHS/local authority-funded access", service_hours:null, notes:"Digital/online support — may be area/partnership dependent", active:true, verified_at:"2025-06-15", last_checked_at:"2025-06-15" },

  // ═══ AUSTRALIA ═══
  { id:"au-aba", country_code:"AU", name:"Australian Breastfeeding Association Helpline", description:"Trained volunteer counsellors — 7 days a week.", support_type:"helpline", support_scope:"national", contact:{phone:"1800 686 268",tdd:null,email:null,whatsapp:null}, source_url:"https://www.breastfeeding.asn.au/breastfeeding-helpline", languages:["en"], region:null, city:null, postcode_prefix:null, lat:null, lng:null, is_24_7:false, is_remote:true, is_in_person:false, trust_level:"registered_charity", trigger_tags:["latch_pain","nipple_pain","low_supply","cluster_feeding","unsettled_after_feeds","engorgement","mastitis_concern","tongue_tie","low_confidence","poor_weight_gain","manual_request"], eligibility:null, service_hours:"7 days a week", notes:null, active:true, verified_at:"2025-06-15", last_checked_at:"2025-06-15" },

  // ═══ NEW ZEALAND ═══
  { id:"nz-plunket", country_code:"NZ", name:"PlunketLine", description:"Free health advice and lactation referral route for all NZ families.", support_type:"helpline", support_scope:"national", contact:{phone:"0800 933 922",tdd:null,email:null,whatsapp:null}, source_url:"https://www.govt.nz/browse/health/free-health-services-for-children/plunketline/", languages:["en","mi"], region:null, city:null, postcode_prefix:null, lat:null, lng:null, is_24_7:true, is_remote:true, is_in_person:false, trust_level:"government", trigger_tags:["latch_pain","nipple_pain","low_supply","cluster_feeding","engorgement","mastitis_concern","poor_weight_gain","dehydration_concern","manual_request"], eligibility:null, service_hours:"24/7", notes:null, active:true, verified_at:"2025-06-15", last_checked_at:"2025-06-15" },

  // ═══ UNITED STATES ═══
  { id:"us-womenshealth", country_code:"US", name:"National Women's Health & Breastfeeding Helpline", description:"Federal helpline — English and Spanish support.", support_type:"helpline", support_scope:"national", contact:{phone:"1-800-994-9662",tdd:"888-220-5446",email:null,whatsapp:null}, source_url:"https://womenshealth.gov/about-us/what-we-do/programs-and-activities/helpline", languages:["en","es"], region:null, city:null, postcode_prefix:null, lat:null, lng:null, is_24_7:false, is_remote:true, is_in_person:false, trust_level:"government", trigger_tags:["latch_pain","nipple_pain","low_supply","cluster_feeding","engorgement","mastitis_concern","tongue_tie","low_confidence","poor_weight_gain","manual_request"], eligibility:null, service_hours:"Mon-Fri 9am-6pm ET", notes:null, active:true, verified_at:"2025-06-15", last_checked_at:"2025-06-15" },

  // ═══ CANADA ═══
  { id:"ca-lllc", country_code:"CA", name:"La Leche League Canada", description:"Peer support with provincial phone lines and local groups.", support_type:"peer_support", support_scope:"national", contact:{phone:"289-350-0303",tdd:null,email:"office@LLLC.ca",whatsapp:null}, source_url:"https://www.lllc.ca/get-help/lllc-phone-lines", languages:["en","fr"], region:null, city:null, postcode_prefix:null, lat:null, lng:null, is_24_7:false, is_remote:true, is_in_person:true, trust_level:"peer_organisation", trigger_tags:["latch_pain","nipple_pain","low_supply","cluster_feeding","engorgement","tongue_tie","low_confidence","manual_request"], eligibility:null, service_hours:null, notes:"Provincial phone lines available — see website", active:true, verified_at:"2025-06-15", last_checked_at:"2025-06-15" },

  // ═══ IRELAND ═══
  { id:"ie-lll", country_code:"IE", name:"La Leche League Ireland", description:"Peer support groups and trained leaders across Ireland.", support_type:"peer_support", support_scope:"national", contact:{phone:null,tdd:null,email:null,whatsapp:null}, source_url:"https://lalecheleague.eu/contact", languages:["en"], region:null, city:null, postcode_prefix:null, lat:null, lng:null, is_24_7:false, is_remote:true, is_in_person:true, trust_level:"peer_organisation", trigger_tags:["latch_pain","low_supply","cluster_feeding","low_confidence","manual_request"], eligibility:null, service_hours:null, notes:null, active:true, verified_at:"2025-06-15", last_checked_at:"2025-06-15" },

  // ═══ FINLAND ═══
  { id:"fi-imetys", country_code:"FI", name:"Imetyksen tuki ry", description:"Finnish breastfeeding peer support organisation.", support_type:"peer_support", support_scope:"national", contact:{phone:null,tdd:null,email:"itu@imetys.fi",whatsapp:null}, source_url:"https://imetys.fi/yhteystiedot/", languages:["fi"], region:null, city:null, postcode_prefix:null, lat:null, lng:null, is_24_7:false, is_remote:true, is_in_person:false, trust_level:"peer_organisation", trigger_tags:["latch_pain","low_supply","cluster_feeding","low_confidence","manual_request"], eligibility:null, service_hours:null, notes:null, active:true, verified_at:"2025-06-15", last_checked_at:"2025-06-15" },
  { id:"fi-rinnalla", country_code:"FI", name:"Rinnalla — English Peer Support", description:"App-based breastfeeding peer support available in English.", support_type:"digital", support_scope:"online", contact:{phone:null,tdd:null,email:null,whatsapp:null}, source_url:"https://imetys.fi/yhdistys/ajankohtaista/breastfeeding-peer-support-available-in-english/", languages:["en"], region:null, city:null, postcode_prefix:null, lat:null, lng:null, is_24_7:false, is_remote:true, is_in_person:false, trust_level:"peer_organisation", trigger_tags:["latch_pain","low_supply","low_confidence","manual_request"], eligibility:null, service_hours:null, notes:"English-language online peer support for Finland-based users", active:true, verified_at:"2025-06-15", last_checked_at:"2025-06-15" },

  // ═══ NORWAY ═══
  { id:"no-ammehjelpen", country_code:"NO", name:"Ammehjelpen", description:"Norwegian breastfeeding peer support.", support_type:"peer_support", support_scope:"national", contact:{phone:null,tdd:null,email:"nettside@ammehjelpen.no",whatsapp:null}, source_url:"https://ammehjelpen.no/ammehjelp/", languages:["no"], region:null, city:null, postcode_prefix:null, lat:null, lng:null, is_24_7:false, is_remote:true, is_in_person:false, trust_level:"peer_organisation", trigger_tags:["latch_pain","low_supply","cluster_feeding","low_confidence","manual_request"], eligibility:null, service_hours:null, notes:null, active:true, verified_at:"2025-06-15", last_checked_at:"2025-06-15" },

  // ═══ SWEDEN ═══
  { id:"se-amningscentrum", country_code:"SE", name:"Amningscentrum, Södersjukhuset", description:"Lactation clinic in Stockholm.", support_type:"lactation_clinic", support_scope:"local", contact:{phone:"08-123 613 25",tdd:null,email:null,whatsapp:null}, source_url:"https://www.1177.se/hitta-vard/kontaktkort/Amningscentrum-Sodersjukhuset/", languages:["sv","en"], region:"Stockholm", city:"Stockholm", postcode_prefix:null, lat:59.3082, lng:18.0400, is_24_7:false, is_remote:false, is_in_person:true, trust_level:"government", trigger_tags:["latch_pain","nipple_pain","tongue_tie","poor_weight_gain","manual_request"], eligibility:null, service_hours:null, notes:"Local Stockholm clinic — via 1177 Vårdguiden", active:true, verified_at:"2025-06-15", last_checked_at:"2025-06-15" },

  // ═══ ISRAEL ═══
  { id:"il-lll", country_code:"IL", name:"La Leche League Israel", description:"Support line and peer support.", support_type:"peer_support", support_scope:"national", contact:{phone:"1599-525-821",tdd:null,email:null,whatsapp:null}, source_url:"https://www.lllisrael.org.il/phone", languages:["he","en"], region:null, city:null, postcode_prefix:null, lat:null, lng:null, is_24_7:false, is_remote:true, is_in_person:false, trust_level:"peer_organisation", trigger_tags:["latch_pain","low_supply","cluster_feeding","low_confidence","manual_request"], eligibility:null, service_hours:null, notes:null, active:true, verified_at:"2025-06-15", last_checked_at:"2025-06-15" },

  // ═══ MEXICO ═══
  { id:"mx-liga", country_code:"MX", name:"La Liga de La Leche México", description:"Peer support with directory by state.", support_type:"peer_support", support_scope:"national", contact:{phone:null,tdd:null,email:null,whatsapp:null}, source_url:"https://laligadelaleche.org.mx/", languages:["es"], region:null, city:null, postcode_prefix:null, lat:null, lng:null, is_24_7:false, is_remote:true, is_in_person:true, trust_level:"peer_organisation", trigger_tags:["latch_pain","low_supply","cluster_feeding","low_confidence","manual_request"], eligibility:null, service_hours:null, notes:"State-level support available", active:true, verified_at:"2025-06-15", last_checked_at:"2025-06-15" },
  { id:"mx-linea-materna", country_code:"MX", name:"Línea Materna", description:"National maternal hotline.", support_type:"hotline", support_scope:"national", contact:{phone:"01 800 628 3762",tdd:null,email:null,whatsapp:null}, source_url:"https://www.unicef.org/mexico/media/1911/file/Guia%20de%20Lactancia%202018.pdf", languages:["es"], region:null, city:null, postcode_prefix:null, lat:null, lng:null, is_24_7:false, is_remote:true, is_in_person:false, trust_level:"government", trigger_tags:["latch_pain","low_supply","mastitis_concern","manual_request"], eligibility:null, service_hours:null, notes:null, active:true, verified_at:"2025-06-15", last_checked_at:"2025-06-15" },
  { id:"mx-edomex", country_code:"MX", name:"Coordinación Estatal de Lactancia Materna — Estado de México", description:"State-level official lactation and milk bank coordination.", support_type:"state_service", support_scope:"regional", contact:{phone:"722 214 75 53",tdd:null,email:"coordinacion.lactanciamaterna@edomex.gob.mx",whatsapp:null}, source_url:"https://salud.edomex.gob.mx/salud/documentos/atencionciudadano/celmbl/material_difusion/2cedulasupervisionbancoleche2025.pdf", languages:["es"], region:"Estado de México", city:null, postcode_prefix:null, lat:null, lng:null, is_24_7:false, is_remote:false, is_in_person:true, trust_level:"government", trigger_tags:["low_supply","mastitis_concern","manual_request"], eligibility:null, service_hours:null, notes:"State-level service for Estado de México", active:true, verified_at:"2025-06-15", last_checked_at:"2025-06-15" },

  // ═══ ARGENTINA ═══
  { id:"ar-liga", country_code:"AR", name:"Liga de La Leche Argentina", description:"Peer breastfeeding support.", support_type:"peer_support", support_scope:"national", contact:{phone:null,tdd:null,email:"info@ligadelaleche.org.ar",whatsapp:null}, source_url:"https://ligadelaleche.org.ar/contacto/", languages:["es"], region:null, city:null, postcode_prefix:null, lat:null, lng:null, is_24_7:false, is_remote:true, is_in_person:false, trust_level:"peer_organisation", trigger_tags:["latch_pain","low_supply","low_confidence","manual_request"], eligibility:null, service_hours:null, notes:null, active:true, verified_at:"2025-06-15", last_checked_at:"2025-06-15" },

  // ═══ CHILE ═══
  { id:"cl-liga", country_code:"CL", name:"Liga de la Leche Chile", description:"Peer breastfeeding support.", support_type:"peer_support", support_scope:"national", contact:{phone:null,tdd:null,email:"contacto@ligadelalechechile.cl",whatsapp:null}, source_url:"https://www.ligadelalechechile.cl/", languages:["es"], region:null, city:null, postcode_prefix:null, lat:null, lng:null, is_24_7:false, is_remote:true, is_in_person:false, trust_level:"peer_organisation", trigger_tags:["latch_pain","low_supply","low_confidence","manual_request"], eligibility:null, service_hours:null, notes:null, active:true, verified_at:"2025-06-15", last_checked_at:"2025-06-15" },

  // ═══ BRAZIL ═══
  { id:"br-lll", country_code:"BR", name:"La Leche League Brasil", description:"Peer breastfeeding support.", support_type:"peer_support", support_scope:"national", contact:{phone:"+55 11 98262-3122",tdd:null,email:null,whatsapp:"+5511982623122"}, source_url:"https://www.lalecheleague-ian.org/lll-brasil.html", languages:["pt"], region:null, city:null, postcode_prefix:null, lat:null, lng:null, is_24_7:false, is_remote:true, is_in_person:false, trust_level:"peer_organisation", trigger_tags:["latch_pain","low_supply","low_confidence","manual_request"], eligibility:null, service_hours:null, notes:null, active:true, verified_at:"2025-06-15", last_checked_at:"2025-06-15" },

  // ═══ INDIA ═══
  { id:"in-lll-chennai", country_code:"IN", name:"La Leche League India — Chennai", description:"Peer support for Chennai area.", support_type:"peer_support", support_scope:"local", contact:{phone:"+91 9710008585",tdd:null,email:"wahida1709@gmail.com",whatsapp:"+919710008585"}, source_url:"https://www.lllasia.org/lll-support-in-india.html", languages:["en","ta"], region:"Tamil Nadu", city:"Chennai", postcode_prefix:null, lat:13.0827, lng:80.2707, is_24_7:false, is_remote:true, is_in_person:true, trust_level:"peer_organisation", trigger_tags:["latch_pain","low_supply","low_confidence","manual_request"], eligibility:null, service_hours:null, notes:null, active:true, verified_at:"2025-06-15", last_checked_at:"2025-06-15" },
  { id:"in-lll-mumbai", country_code:"IN", name:"La Leche League India — Mumbai", description:"Peer support for Mumbai area.", support_type:"peer_support", support_scope:"local", contact:{phone:"+91 9819890069",tdd:null,email:"effathyasmin@gmail.com",whatsapp:"+919819890069"}, source_url:"https://www.lllasia.org/lll-support-in-india.html", languages:["en","hi","mr"], region:"Maharashtra", city:"Mumbai", postcode_prefix:null, lat:19.0760, lng:72.8777, is_24_7:false, is_remote:true, is_in_person:true, trust_level:"peer_organisation", trigger_tags:["latch_pain","low_supply","low_confidence","manual_request"], eligibility:null, service_hours:null, notes:null, active:true, verified_at:"2025-06-15", last_checked_at:"2025-06-15" },
  { id:"in-lll-delhi", country_code:"IN", name:"La Leche League India — New Delhi", description:"Peer support for Delhi area.", support_type:"peer_support", support_scope:"local", contact:{phone:"+91 9810059391",tdd:null,email:"himani.dalmia@gmail.com",whatsapp:"+919810059391"}, source_url:"https://www.lllasia.org/lll-support-in-india.html", languages:["en","hi"], region:"Delhi", city:"New Delhi", postcode_prefix:null, lat:28.6139, lng:77.2090, is_24_7:false, is_remote:true, is_in_person:true, trust_level:"peer_organisation", trigger_tags:["latch_pain","low_supply","low_confidence","manual_request"], eligibility:null, service_hours:null, notes:null, active:true, verified_at:"2025-06-15", last_checked_at:"2025-06-15" },

  // ═══ SINGAPORE ═══
  { id:"sg-lll", country_code:"SG", name:"La Leche League Singapore", description:"Peer breastfeeding support.", support_type:"peer_support", support_scope:"national", contact:{phone:"+65 9177 2024",tdd:null,email:"lalechesingapore@gmail.com",whatsapp:"+6591772024"}, source_url:"https://www.lllasia.org/lll-support-in-singapore.html", languages:["en"], region:null, city:null, postcode_prefix:null, lat:null, lng:null, is_24_7:false, is_remote:true, is_in_person:true, trust_level:"peer_organisation", trigger_tags:["latch_pain","low_supply","low_confidence","manual_request"], eligibility:null, service_hours:null, notes:null, active:true, verified_at:"2025-06-15", last_checked_at:"2025-06-15" },

  // ═══ MALAYSIA ═══
  { id:"my-lll", country_code:"MY", name:"La Leche League Kuala Lumpur — Ampang", description:"Peer support for KL area.", support_type:"peer_support", support_scope:"local", contact:{phone:"+60 12 415 6353",tdd:null,email:"michelle.l.byrom@gmail.com",whatsapp:"+60124156353"}, source_url:"https://www.lllasia.org/lll-support-in-malaysia.html", languages:["en","ms"], region:"Selangor", city:"Kuala Lumpur", postcode_prefix:null, lat:3.1390, lng:101.6869, is_24_7:false, is_remote:true, is_in_person:true, trust_level:"peer_organisation", trigger_tags:["latch_pain","low_supply","low_confidence","manual_request"], eligibility:null, service_hours:null, notes:null, active:true, verified_at:"2025-06-15", last_checked_at:"2025-06-15" },

  // ═══ INDONESIA ═══
  { id:"id-lll", country_code:"ID", name:"La Leche League Indonesia", description:"Peer breastfeeding support.", support_type:"peer_support", support_scope:"national", contact:{phone:"+62 8111-66524",tdd:null,email:"monika.lll.leader@gmail.com",whatsapp:"+62811166524"}, source_url:"https://www.lllasia.org/lll-support-in-indonesia.html", languages:["id","en"], region:null, city:null, postcode_prefix:null, lat:null, lng:null, is_24_7:false, is_remote:true, is_in_person:false, trust_level:"peer_organisation", trigger_tags:["latch_pain","low_supply","low_confidence","manual_request"], eligibility:null, service_hours:null, notes:"West Java support entry", active:true, verified_at:"2025-06-15", last_checked_at:"2025-06-15" },

  // ═══ UAE ═══
  { id:"ae-lll", country_code:"AE", name:"La Leche League UAE", description:"Peer support covering Abu Dhabi and Dubai.", support_type:"peer_support", support_scope:"national", contact:{phone:null,tdd:null,email:null,whatsapp:null}, source_url:"https://www.lllasia.org/lll-support-in-uae.html", languages:["en","ar"], region:null, city:null, postcode_prefix:null, lat:null, lng:null, is_24_7:false, is_remote:true, is_in_person:true, trust_level:"peer_organisation", trigger_tags:["latch_pain","low_supply","low_confidence","manual_request"], eligibility:null, service_hours:null, notes:"Abu Dhabi and Dubai coverage", active:true, verified_at:"2025-06-15", last_checked_at:"2025-06-15" },

  // ═══ SOUTH AFRICA ═══
  { id:"za-lll", country_code:"ZA", name:"La Leche League South Africa", description:"Provincial peer support contacts.", support_type:"peer_support", support_scope:"national", contact:{phone:null,tdd:null,email:null,whatsapp:null}, source_url:"https://www.lllsa.org/westerncape", languages:["en","af"], region:null, city:null, postcode_prefix:null, lat:null, lng:null, is_24_7:false, is_remote:true, is_in_person:true, trust_level:"peer_organisation", trigger_tags:["latch_pain","low_supply","low_confidence","manual_request"], eligibility:null, service_hours:null, notes:"Provincial contacts available on website", active:true, verified_at:"2025-06-15", last_checked_at:"2025-06-15" },

  // ═══ BOTSWANA ═══
  { id:"bw-lll", country_code:"BW", name:"LLLSA Botswana", description:"Peer support in Gaborone area.", support_type:"peer_support", support_scope:"local", contact:{phone:"+267 7407 5744",tdd:null,email:null,whatsapp:"+26774075744"}, source_url:"https://www.lllsa.org/botswana", languages:["en","tn"], region:null, city:"Gaborone", postcode_prefix:null, lat:-24.6282, lng:25.9231, is_24_7:false, is_remote:true, is_in_person:true, trust_level:"peer_organisation", trigger_tags:["latch_pain","low_supply","manual_request"], eligibility:null, service_hours:null, notes:"Also reachable at +267 7447 2690", active:true, verified_at:"2025-06-15", last_checked_at:"2025-06-15" },

  // ═══ KENYA ═══
  { id:"ke-lll", country_code:"KE", name:"LLLSA Kenya", description:"Peer support in Nairobi area.", support_type:"peer_support", support_scope:"local", contact:{phone:"+254 708 407480",tdd:null,email:null,whatsapp:"+254708407480"}, source_url:"https://www.lllsa.org/kenya", languages:["en","sw"], region:null, city:"Nairobi", postcode_prefix:null, lat:-1.2921, lng:36.8219, is_24_7:false, is_remote:true, is_in_person:true, trust_level:"peer_organisation", trigger_tags:["latch_pain","low_supply","manual_request"], eligibility:null, service_hours:null, notes:null, active:true, verified_at:"2025-06-15", last_checked_at:"2025-06-15" },

  // ═══ ZIMBABWE ═══
  { id:"zw-lll", country_code:"ZW", name:"LLLSA Zimbabwe", description:"Peer support in Harare area.", support_type:"peer_support", support_scope:"local", contact:{phone:"+263 78 518 3350",tdd:null,email:null,whatsapp:"+263785183350"}, source_url:"https://www.lllsa.org/zimbabwe", languages:["en","sn"], region:null, city:"Harare", postcode_prefix:null, lat:-17.8252, lng:31.0335, is_24_7:false, is_remote:true, is_in_person:true, trust_level:"peer_organisation", trigger_tags:["latch_pain","low_supply","manual_request"], eligibility:null, service_hours:null, notes:null, active:true, verified_at:"2025-06-15", last_checked_at:"2025-06-15" },
];

// Country name lookup
export const COUNTRY_NAMES = {
  GB:"United Kingdom", US:"United States", AU:"Australia", NZ:"New Zealand",
  CA:"Canada", IE:"Ireland", FI:"Finland", NO:"Norway", SE:"Sweden",
  IL:"Israel", MX:"Mexico", AR:"Argentina", CL:"Chile", BR:"Brazil",
  IN:"India", SG:"Singapore", MY:"Malaysia", ID:"Indonesia", AE:"UAE",
  ZA:"South Africa", BW:"Botswana", KE:"Kenya", ZW:"Zimbabwe",
  DE:"Germany", FR:"France", NL:"Netherlands", DK:"Denmark", ES:"Spain",
  IT:"Italy", PT:"Portugal", JP:"Japan", KR:"South Korea", GLOBAL:"Global"
};
